# @name createProduct
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Product A",
  "price": 100.0
}

###

GET http://localhost:8080/products/078565a1357e47f3a0a4fd664d41b411 HTTP/1.1
Content-Type: application/json
